version = 1

test_patterns = ["tests/**"]
exclude_patterns = ["dist/**", "styled-system/**", ".astro/**", "coverage/**", "public/**"]

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  environment = ["nodejs", "browser", "vitest"]
  dialect = "typescript"

[[analyzers]]
name = "test-coverage"
enabled = true
